server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

azure:
  activedirectory:
    client-id: XXXXXXX
    client-secret: XXXXXXX
    tenant-id: XXXXXX
    userNameAttribute: preferred_username
    post-logout-redirect-uri: http://localhost:8080
    authorization-clients:
      graph:
        scopes:
          - https://graph.microsoft.com/User.Read.All
